### ISSUE TITLE
运行错误，缺少checkpoints/pytorch_model.bin

### ISSUE THREAD

**Issue by kiko175457** [YanzuoLu/CFLD#35]
100%|███████████████████████████████████████████████████████████████████████████████████████████| 233M/233M [00:16<00:00, 14.9MB/s]
Traceback (most recent call last):
  File "/home/liu/demo/CFLD/pose_transfer_test.py", line 511, in <module>
    main(cfg)
  File "/home/liu/demo/CFLD/pose_transfer_test.py", line 465, in main
    logger.info(model.load_state_dict(torch.load(
  File "/home/liu/miniconda3/envs/CFLD/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/liu/miniconda3/envs/CFLD/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/liu/miniconda3/envs/CFLD/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/pytorch_model.bin'

**Comment by YanzuoLu** [comment]
Hi @kiko175457 
Please refer to https://github.com/YanzuoLu/CFLD?tab=readme-ov-file#inference and specify MODEL.PRETRAINED_PATH.
